### ISSUE TITLE
Doesn't work with epsxe savestates.

### ISSUE THREAD

**Issue by tcaudilllg** [romhack/PsxVram-SDL#2]
As of v.2.0.5 . Produces static only.

**Comment by romhack** [comment]
I could not reproduce the issue.
Could you please delete 'vram.bin' file in root directory and load dump directly via 
"PsxVram-SDL your_dump_name.bin"?

**Comment by aybe** [comment]
@tcaudilllg It does, make sure you unzip them first.

**Comment by romhack** [comment]
Most probably, savestate was default compressed. You need to decompress it by hand. In case of NO$PSX make sure settings are 'uncompressed' for savestates.
