### ISSUE TITLE
Size Window

### ISSUE THREAD

**Issue by DavidAshta** [romhack/PsxVram-SDL#4]
![BACGROUND REQUEST](https://user-images.githubusercontent.com/23743522/104823020-c8278700-5825-11eb-8c4f-4b47587c3d5c.PNG)
[SLPS_035.zip](https://github.com/romhack/PsxVram-SDL/files/5825130/SLPS_035.zip)

Hey, ive tested with the new release, but it stills open like this, i'm sending you the file too, so you can test it too ;)

**Comment by DavidAshta** [comment]
I don't know if I'm doing something wrong, i was in a hurry to go to my work so, i just did the same options to see if i can get the background, but as you can see i just got the "almost middle" of it
can i make a suggestion? since I'm big user of this tool, the old version was great, it's had one problem thought, the sprites seems blurry and on bad quality since we can't save them just print it, this new version is great because the sprites looks in a a great shape (original one without being in bad quality)
but could you make this happen in the old version of PSXVram? just update the quality of sprites in the old version like in the new one would be great ;D , for real this tool have the potential to be a great thing, i already did many rips with it, but i like the old version, if you just can update the old version with the quality of the sprites from this new one would be great

**Comment by romhack** [comment]
I believe, the issue is in the mode viewer window size?
Have you tried to use 'Shift + (W/A/S/D)' to change it?

**Comment by DavidAshta** [comment]
i tried already it too, but its keeps on the middle cutting the background
if we can extend both the windows to full mode or move it freely probably would solve it ;)

**Comment by DavidAshta** [comment]
looks like it worked with Shift + WSAD, Thank You! but like i said yesterday, i was in a hurry so i didnt tested properly, Closed Issue! ;) Thank You again!

**Comment by romhack** [comment]
No problem, I have also updated readme to cover this.
BTW, do you have additional feature requests for your riping activity, like saving to png or something?

**Comment by DavidAshta** [comment]
would be great if we have the "Save PNG Button"  ;)

**Comment by romhack** [comment]
Latest release now has 'Save to BMP' feature (hotkey P).

I'm actually thinking about switching to normal GUI with C#, but not sure if this is requred by any users.

**Comment by DavidAshta** [comment]
why not? more updates on this tool would be amazing, let's see how it goes
