### ISSUE TITLE
not a issue, but..

### ISSUE THREAD

**Issue by DavidAshta** [romhack/PsxVram-SDL#9]
BMP is great! but how about if we keep pressing P and saving more files without we renaming it, it would be very fast and helpful and having a Background change color, some characters have black hair and more aspects like that, and for editing, having a white background or more colors would be great cause we can see the sprite of the character in a good way ;)

**Comment by romhack** [comment]
Thank you for ideas! I'm currently re-writing the whole thing for normal .net GUI, so this will be in my features list for sure!

**Comment by DavidAshta** [comment]
if i come with more helpful ideas i'll share! (using the latest version right now [[AMAZING]] Currently Ripping Yu-Gi-Oh Forbidden Memories)

**Comment by romhack** [comment]
Implemented your request in[ PsxVram-DotNet application](https://github.com/romhack/PsxVram-DotNet). Please check that repository, it has almost all old features, except savestates handling.  
 PsxVram-SDL is discontinued.
